###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 250
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 20
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  TRAIN_DIR: './Datasets/Seasons/train/'       # path to training data
  VAL_DIR: './Datasets/Seasons/val/' # path to validation data
  SAVE_DIR: './checkpoint'           # path to save models and images
  SAVE_IMAGES: True
